# Generated by Django 5.1.2 on 2024-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuscleExercise',
            new_name='Muscle_Exercise',
        ),
    ]
